#!/usr/bin/env python3
"""
AI Fitness Dashboard - Interactive Setup Script
================================================
This script helps configure your AI Fitness system by:
1. Installing required dependencies
2. Configuring integrations (Garmin, Hevy, Gemini AI)
3. Setting up scheduled tasks
4. Configuring dashboard autostart

Run with: python3 setup.py
"""

import os
import sys
import subprocess
import getpass
import platform
from pathlib import Path

# Colors for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}  {text}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}\n")

def print_section(text):
    print(f"\n{Colors.CYAN}{Colors.BOLD}--- {text} ---{Colors.END}\n")

def print_success(text):
    print(f"{Colors.GREEN}[OK] {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.YELLOW}[!] {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}[ERROR] {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}[i] {text}{Colors.END}")

def ask_yes_no(question, default=True):
    """Ask a yes/no question and return boolean."""
    suffix = " [Y/n]: " if default else " [y/N]: "
    while True:
        response = input(f"{question}{suffix}").strip().lower()
        if response == "":
            return default
        if response in ("y", "yes"):
            return True
        if response in ("n", "no"):
            return False
        print("Please answer 'y' or 'n'")

def ask_input(prompt, default=None, password=False):
    """Ask for input with optional default value."""
    if default:
        display = f"{prompt} [{default}]: "
    else:
        display = f"{prompt}: "

    if password:
        value = getpass.getpass(display)
    else:
        value = input(display).strip()

    return value if value else default

def get_script_dir():
    """Get the directory where this script is located."""
    return Path(__file__).parent.absolute()

def load_existing_env():
    """Load existing .env file if it exists."""
    env_file = get_script_dir() / ".env"
    env_vars = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    return env_vars

def save_env(env_vars):
    """Save environment variables to .env file."""
    env_file = get_script_dir() / ".env"

    with open(env_file, 'w') as f:
        f.write("# AI Fitness Dashboard Configuration\n")
        f.write("# Generated by setup.py\n\n")

        # Group by category
        categories = {
            'paths': ['SAVE_PATH', 'DRIVE_MOUNT_PATH', 'PROJECT_DIR', 'LOG_FILE'],
            'garmin': ['GARMIN_EMAIL', 'GARMIN_PASSWORD'],
            'hevy': ['HEVY_API_KEY'],
            'google': ['GEMINI_API_KEY', 'GOOGLE_DRIVE_FOLDER_ID'],
            'system': ['CHECK_MOUNT_STATUS', 'FLASK_SECRET_KEY', 'DASHBOARD_PORT']
        }

        category_names = {
            'paths': '# File Paths',
            'garmin': '# Garmin Connect',
            'hevy': '# Hevy App',
            'google': '# Google Services',
            'system': '# System Settings'
        }

        written_keys = set()

        for cat, keys in categories.items():
            cat_vars = {k: v for k, v in env_vars.items() if k in keys}
            if cat_vars:
                f.write(f"\n{category_names[cat]}\n")
                for key in keys:
                    if key in env_vars:
                        f.write(f"{key}={env_vars[key]}\n")
                        written_keys.add(key)

        # Write any remaining variables
        remaining = {k: v for k, v in env_vars.items() if k not in written_keys}
        if remaining:
            f.write("\n# Other Settings\n")
            for key, value in remaining.items():
                f.write(f"{key}={value}\n")

    print_success(f"Configuration saved to {env_file}")

def install_dependencies():
    """Install required Python packages."""
    print_section("Installing Dependencies")

    requirements_file = get_script_dir() / "requirements.txt"

    if not requirements_file.exists():
        print_error("requirements.txt not found!")
        return False

    print_info("Installing Python packages from requirements.txt...")
    print_info("This may take a few minutes...")

    try:
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", str(requirements_file)],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print_success("All dependencies installed successfully!")
            return True
        else:
            print_error(f"pip install failed: {result.stderr}")
            return False
    except Exception as e:
        print_error(f"Failed to install dependencies: {e}")
        return False

def configure_paths(env_vars):
    """Configure file paths."""
    print_section("File Paths Configuration")

    is_pi = platform.machine().startswith('arm') or platform.machine() == 'aarch64'

    print_info("Where should data files be saved?")
    print_info("This is where CSV files (hevy_stats.csv, garmin_stats.csv, etc.) will be stored.")

    if is_pi:
        default_save = env_vars.get('SAVE_PATH', '/home/pi/GDrive/Gemini Gems/Personal trainer')
        default_mount = env_vars.get('DRIVE_MOUNT_PATH', '/home/pi/GDrive')
    else:
        default_save = env_vars.get('SAVE_PATH', str(Path.home() / 'AI_Fitness_Data'))
        default_mount = env_vars.get('DRIVE_MOUNT_PATH', '')

    env_vars['SAVE_PATH'] = ask_input("Data save path", default_save)

    # Create directory if it doesn't exist
    save_path = Path(env_vars['SAVE_PATH'])
    if not save_path.exists():
        if ask_yes_no(f"Directory '{save_path}' doesn't exist. Create it?"):
            try:
                save_path.mkdir(parents=True, exist_ok=True)
                print_success(f"Created directory: {save_path}")
            except Exception as e:
                print_warning(f"Could not create directory: {e}")

    if is_pi:
        print_info("\nRaspberry Pi detected. Configure Google Drive mount?")
        if ask_yes_no("Do you use rclone/Google Drive mount?"):
            env_vars['DRIVE_MOUNT_PATH'] = ask_input("Drive mount path", default_mount)
            env_vars['CHECK_MOUNT_STATUS'] = 'True'
        else:
            env_vars['CHECK_MOUNT_STATUS'] = 'False'
    else:
        env_vars['CHECK_MOUNT_STATUS'] = 'False'

    return env_vars

def configure_garmin(env_vars):
    """Configure Garmin Connect integration."""
    print_section("Garmin Connect Configuration")

    print_info("Garmin Connect tracks your health metrics (sleep, HRV, weight, etc.)")
    print_info("You need a Garmin account and a compatible Garmin device.")
    print()

    if not ask_yes_no("Do you want to use Garmin Connect integration?"):
        print_info("Skipping Garmin configuration.")
        return env_vars, False

    print()
    print_info("Enter your Garmin Connect credentials:")
    print_warning("These are stored locally in .env and used to sync your health data.")
    print()

    current_email = env_vars.get('GARMIN_EMAIL', '')
    if current_email:
        print_info(f"Current email: {current_email}")
        if not ask_yes_no("Keep current credentials?"):
            env_vars['GARMIN_EMAIL'] = ask_input("Garmin email")
            env_vars['GARMIN_PASSWORD'] = ask_input("Garmin password", password=True)
    else:
        env_vars['GARMIN_EMAIL'] = ask_input("Garmin email")
        env_vars['GARMIN_PASSWORD'] = ask_input("Garmin password", password=True)

    # Test Garmin login
    print_info("\nTesting Garmin login...")
    try:
        import garth
        garth.login(env_vars['GARMIN_EMAIL'], env_vars['GARMIN_PASSWORD'])
        garth.save(".garth")
        print_success("Garmin login successful! Tokens saved.")
        return env_vars, True
    except Exception as e:
        print_error(f"Garmin login failed: {e}")
        print_warning("You can fix this later and run: python3 setup_garmin_login.py")
        return env_vars, False

def configure_hevy(env_vars):
    """Configure Hevy App integration."""
    print_section("Hevy App Configuration")

    print_info("Hevy is a workout tracking app that logs your strength training.")
    print_info("You need a Hevy account and API key to sync workouts.")
    print()
    print_info("To get your API key:")
    print_info("  1. Open Hevy app or web (https://hevy.com)")
    print_info("  2. Go to Settings > Account > API")
    print_info("  3. Copy your API key")
    print()

    if not ask_yes_no("Do you want to use Hevy integration?"):
        print_info("Skipping Hevy configuration.")
        return env_vars, False

    current_key = env_vars.get('HEVY_API_KEY', '')
    if current_key:
        masked = current_key[:8] + "..." + current_key[-4:] if len(current_key) > 12 else "***"
        print_info(f"Current API key: {masked}")
        if not ask_yes_no("Keep current API key?"):
            env_vars['HEVY_API_KEY'] = ask_input("Hevy API key")
    else:
        env_vars['HEVY_API_KEY'] = ask_input("Hevy API key")

    # Test Hevy API
    if env_vars.get('HEVY_API_KEY'):
        print_info("\nTesting Hevy API...")
        try:
            import requests
            response = requests.get(
                "https://api.hevyapp.com/v1/workouts",
                headers={"api-key": env_vars['HEVY_API_KEY']},
                params={"page": 1, "pageSize": 1}
            )
            if response.status_code == 200:
                print_success("Hevy API connection successful!")
                return env_vars, True
            else:
                print_error(f"Hevy API error: {response.status_code}")
                return env_vars, False
        except Exception as e:
            print_error(f"Failed to test Hevy API: {e}")
            return env_vars, False

    return env_vars, False

def configure_gemini(env_vars):
    """Configure Google Gemini AI integration."""
    print_section("Gemini AI Configuration")

    print_info("Gemini AI generates personalized monthly workout plans.")
    print_info("This requires a Google AI API key and Google Drive access.")
    print()
    print_info("To get your Gemini API key:")
    print_info("  1. Go to https://aistudio.google.com/apikey")
    print_info("  2. Create a new API key")
    print_info("  3. Copy the key")
    print()

    if not ask_yes_no("Do you want to use Gemini AI for workout planning?"):
        print_info("Skipping Gemini configuration.")
        return env_vars, False

    current_key = env_vars.get('GEMINI_API_KEY', '')
    if current_key:
        masked = current_key[:8] + "..." if len(current_key) > 8 else "***"
        print_info(f"Current API key: {masked}")
        if not ask_yes_no("Keep current API key?"):
            env_vars['GEMINI_API_KEY'] = ask_input("Gemini API key")
    else:
        env_vars['GEMINI_API_KEY'] = ask_input("Gemini API key")

    print()
    print_info("Google Drive Folder ID (for Chat Memory spreadsheet):")
    print_info("  1. Open your Google Drive folder in browser")
    print_info("  2. The URL looks like: drive.google.com/drive/folders/FOLDER_ID")
    print_info("  3. Copy the FOLDER_ID part")
    print()

    current_folder = env_vars.get('GOOGLE_DRIVE_FOLDER_ID', '')
    if current_folder:
        print_info(f"Current folder ID: {current_folder}")
        if not ask_yes_no("Keep current folder ID?"):
            env_vars['GOOGLE_DRIVE_FOLDER_ID'] = ask_input("Google Drive folder ID")
    else:
        env_vars['GOOGLE_DRIVE_FOLDER_ID'] = ask_input("Google Drive folder ID (or leave empty)")

    return env_vars, True

def setup_cron_tasks():
    """Help user set up scheduled tasks."""
    print_section("Scheduled Tasks Setup")

    is_pi = platform.machine().startswith('arm') or platform.machine() == 'aarch64'

    if not is_pi:
        print_warning("Cron scheduling is typically used on Raspberry Pi/Linux.")
        print_info("On Windows, use Task Scheduler instead.")
        if not ask_yes_no("Continue with cron setup anyway?", default=False):
            return

    print_info("This will help you set up automatic data syncing.")
    print_info("Tasks can run hourly, daily, etc.")
    print()

    if not ask_yes_no("Set up scheduled tasks?"):
        return

    script_dir = get_script_dir()

    cron_jobs = []

    print()
    if ask_yes_no("Schedule Garmin health data sync? (recommended: hourly)"):
        cron_jobs.append(f"30 * * * * cd {script_dir} && /usr/bin/python3 daily_garmin_health.py >> /home/pi/cron_log.txt 2>&1")

    if ask_yes_no("Schedule Hevy workout sync? (recommended: hourly)"):
        cron_jobs.append(f"35 * * * * cd {script_dir} && /usr/bin/python3 daily_hevy_workouts.py >> /home/pi/cron_log.txt 2>&1")

    if ask_yes_no("Schedule Garmin runs sync? (recommended: hourly)"):
        cron_jobs.append(f"40 * * * * cd {script_dir} && /usr/bin/python3 daily_garmin_runs.py >> /home/pi/cron_log.txt 2>&1")

    if ask_yes_no("Schedule monthly AI workout plan generation?"):
        cron_jobs.append(f"0 1 1 * * cd {script_dir} && {script_dir}/venv/bin/python Gemini_Hevy.py >> /home/pi/cron_log.txt 2>&1")

    if cron_jobs:
        print()
        print_info("Add these lines to your crontab:")
        print_info("Run: crontab -e")
        print()
        for job in cron_jobs:
            print(f"  {job}")
        print()
        print_info("Or run this command to add them automatically:")
        print(f"  (crontab -l 2>/dev/null; echo '{cron_jobs[0]}') | crontab -")

def setup_dashboard_autostart():
    """Set up dashboard to start on boot."""
    print_section("Dashboard Autostart Setup")

    is_pi = platform.machine().startswith('arm') or platform.machine() == 'aarch64'

    if not is_pi:
        print_warning("Autostart setup is designed for Raspberry Pi.")
        if not ask_yes_no("Continue anyway?", default=False):
            return

    print_info("This will configure the dashboard to start automatically on boot.")
    print()

    if not ask_yes_no("Set up dashboard autostart?"):
        return

    script_dir = get_script_dir()
    service_content = f"""[Unit]
Description=AI Fitness Dashboard
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory={script_dir}
ExecStart={script_dir}/venv/bin/streamlit run dashboard_local_server.py --server.port 8501 --server.address 0.0.0.0
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
"""

    service_file = script_dir / "ai-fitness-dashboard.service"

    with open(service_file, 'w') as f:
        f.write(service_content)

    print_success(f"Service file created: {service_file}")
    print()
    print_info("To enable the service, run these commands:")
    print(f"  sudo cp {service_file} /etc/systemd/system/")
    print("  sudo systemctl daemon-reload")
    print("  sudo systemctl enable ai-fitness-dashboard")
    print("  sudo systemctl start ai-fitness-dashboard")
    print()
    print_info("To check status: sudo systemctl status ai-fitness-dashboard")

def run_initial_imports():
    """Offer to run initial data imports."""
    print_section("Initial Data Import")

    print_info("Would you like to import historical data?")
    print_info("This pulls your past workout and health data.")
    print()

    if not ask_yes_no("Run any history imports?", default=False):
        return

    # Ask for start date
    print()
    print_info("How far back should we import data?")
    print_info("Enter a date in YYYY-MM-DD format (e.g., 2023-01-01)")
    print()

    from datetime import datetime, timedelta
    default_date = (datetime.now() - timedelta(days=365)).strftime("%Y-%m-%d")
    start_date = ask_input("Start date", default_date)

    # Validate date format
    try:
        datetime.strptime(start_date, "%Y-%m-%d")
    except ValueError:
        print_error(f"Invalid date format: {start_date}. Using default: {default_date}")
        start_date = default_date

    print()
    script_dir = get_script_dir()

    if ask_yes_no("Import Hevy workout history?", default=False):
        print_info(f"Running Hevy history import from {start_date}...")
        try:
            subprocess.run([sys.executable, str(script_dir / "history_hevy_import.py"), start_date])
        except Exception as e:
            print_error(f"Failed: {e}")

    if ask_yes_no("Import Garmin health history?", default=False):
        print_info(f"Running Garmin health history import from {start_date}...")
        try:
            subprocess.run([sys.executable, str(script_dir / "history_garmin_import.py"), start_date])
        except Exception as e:
            print_error(f"Failed: {e}")

    if ask_yes_no("Import Garmin runs history?", default=False):
        print_info(f"Running Garmin runs history import from {start_date}...")
        try:
            subprocess.run([sys.executable, str(script_dir / "history_garmin_runs.py"), start_date])
        except Exception as e:
            print_error(f"Failed: {e}")

def main():
    """Main setup wizard."""
    print_header("AI Fitness Dashboard Setup")

    print("Welcome to the AI Fitness Dashboard setup wizard!")
    print("This will help you configure your fitness tracking system.")
    print()
    print("You can re-run this script at any time to update settings.")
    print()

    if not ask_yes_no("Ready to begin?"):
        print("Setup cancelled.")
        return

    # Load existing configuration
    env_vars = load_existing_env()

    # Track which services are enabled
    services = {
        'garmin': False,
        'hevy': False,
        'gemini': False
    }

    # Step 1: Install dependencies
    if ask_yes_no("\nInstall/update Python dependencies?"):
        install_dependencies()

    # Step 2: Configure paths
    env_vars = configure_paths(env_vars)

    # Step 3: Configure integrations
    env_vars, services['garmin'] = configure_garmin(env_vars)
    env_vars, services['hevy'] = configure_hevy(env_vars)
    env_vars, services['gemini'] = configure_gemini(env_vars)

    # Generate Flask secret key if not present
    if 'FLASK_SECRET_KEY' not in env_vars:
        import secrets
        env_vars['FLASK_SECRET_KEY'] = secrets.token_hex(32)

    # Save configuration
    save_env(env_vars)

    # Step 4: Scheduled tasks
    setup_cron_tasks()

    # Step 5: Dashboard autostart
    setup_dashboard_autostart()

    # Step 6: Initial imports
    run_initial_imports()

    # Summary
    print_header("Setup Complete!")

    print("Enabled services:")
    if services['garmin']:
        print_success("  Garmin Connect - Health tracking")
    else:
        print_warning("  Garmin Connect - Not configured")

    if services['hevy']:
        print_success("  Hevy - Workout tracking")
    else:
        print_warning("  Hevy - Not configured")

    if services['gemini']:
        print_success("  Gemini AI - Workout planning")
    else:
        print_warning("  Gemini AI - Not configured")

    print()
    print_info("To start the dashboard now, run:")
    print(f"  cd {get_script_dir()}")
    print("  streamlit run dashboard_local_server.py")
    print()
    print_info("Or if using a virtual environment:")
    print("  ./venv/bin/streamlit run dashboard_local_server.py")
    print()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(0)
